# -----------------------------------------------------------------------------
# Tokyo Night Storm skin for k9s
# Based on folke's nvim-tokyonight Storm variant
# -----------------------------------------------------------------------------
# Styles...
foreground: &foreground "#c0caf5"
background: &background "default" # Transparent
current_line: &current_line "#292e42"
selection: &selection "#364a82"
comment: &comment "#565f89"
cyan: &cyan "#7dcfff"
green: &green "#9ece6a"
orange: &orange "#ff9e64"
pink: &pink "#bb9af7"
purple: &purple "#9d7cd8"
red: &red "#f7768e"
yellow: &yellow "#e0af68"
blue: &blue "#7aa2f7"
teal: &teal "#1abc9c"
# Skin...
k9s:
  # General K9s styles
  body:
    fgColor: *cyan
    bgColor: *background
    logoColor: *purple
  # Command prompt styles
  prompt:
    fgColor: *cyan
    bgColor: *background
    suggestColor: *pink
  # ClusterInfoView styles.
  info:
    fgColor: *pink
    sectionColor: *blue
  # Dialog styles.
  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *purple
    buttonFocusFgColor: *current_line
    buttonFocusBgColor: *cyan
    labelFgColor: *yellow
    fieldFgColor: *cyan
  frame:
    # Borders styles.
    border:
      fgColor: *purple
      focusColor: *cyan
    menu:
      fgColor: *cyan
      keyColor: *pink
      # Used for favorite namespaces
      numKeyColor: *orange
    # CrumbView attributes for history navigation.
    crumbs:
      fgColor: *cyan
      bgColor: *current_line
      activeColor: *pink
    # Resource status and update styles
    status:
      newColor: *green
      modifyColor: *orange
      addColor: *cyan
      errorColor: *red
      highlightColor: *yellow
      killColor: *comment
      completedColor: *purple
    # Border title styles.
    title:
      fgColor: *cyan
      bgColor: *current_line
      highlightColor: *pink
      counterColor: *yellow
      filterColor: *orange
  views:
    # Charts skins...
    charts:
      bgColor: default
      defaultDialColors:
        - *purple
        - *cyan
        - *pink
      defaultChartColors:
        - *purple
        - *cyan
        - *pink
    # TableView attributes.
    table:
      fgColor: *cyan
      bgColor: *background
      # Header row styles.
      header:
        fgColor: *pink
        bgColor: *background
        sorterColor: *yellow
    # Xray view attributes.
    xray:
      fgColor: *cyan
      bgColor: *background
      cursorColor: *current_line
      graphicColor: *purple
      showIcons: false
    # YAML info styles.
    yaml:
      keyColor: *pink
      colonColor: *purple
      valueColor: *cyan
    # Logs styles.
    logs:
      fgColor: *cyan
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *purple
        toggleOnColor: *green
        toggleOffColor: *red
