auto_sync = false
update_check = false
search_mode = "fuzzy"
workspaces = false
filter_mode_shell_up_key_binding = "global"
search_mode_shell_up_key_binding = "fuzzy"
style = "auto"
store_failed = true
history_filter = [
  "^secret-cmd",
  "^innocuous-cmd .*--secret=.+",
  "^l$",
  "^ls$",
  "^c$",
  "^clear$",
]
secrets_filter = true
enter_accept = false
keymap_mode = "auto"
prefers_reduced_motion = true
ignored_commands = ["cd", "ls", "vi", "nvim", "vim", "l", "c"]
smart_sort = true
