auto_sync = false
update_check = false
search_mode = "fuzzy"
workspaces = false
filter_mode_shell_up_key_binding = "global"
search_mode_shell_up_key_binding = "fuzzy"
style = "auto"
store_failed = false
history_filter = [
  "^secret-cmd",
  "^innocuous-cmd .*--secret=.+",
  "^l$",
  "^ls$",
  "^c$",
  "^clear$",
]
secrets_filter = false
enter_accept = false
keymap_mode = "auto"
prefers_reduced_motion = true
[stats]
ignored_commands = ["cd", "ls", "vi", "nvim", "vim", "l", "c"]
[keys]
daemon = true
smart_sort = true
