#!/bin/zsh
# This script is used to deploy this folder dotfiles config to the right directories

# Define the base path for all configurations
BASE_CONFIG_PATH="$HOME/.config/"

CONFIG_FOLDERS=(
  "tmux"
  "sway"
  "mako"
  "fuzzel"
  "alacritty"
  "sway-interactive-screenshot"
  "k9s"
  "lvim"
  "wob"
  "newsboat"
  "containers"
  "ncspot"
  "rescrobbled"
  "systemd/user"
)

# Create destination folders and symlinks for files in each folder
for folder in "${CONFIG_FOLDERS[@]}"; do
  destination_path="$BASE_CONFIG_PATH$folder"
  mkdir -p "$destination_path"
  ln -sf "$DOTFILES/$folder/"* "$destination_path/"
  echo "Symlinked files in $folder to $destination_path"
done

# FILES
ln -sf "$DOTFILES/.zshrc" ~/.zshrc
ln -sf "$DOTFILES/.zshenv" ~/.zshenv
echo "Symlinked .zshrc && .zshenv"

echo "Dotfiles deployment completed successfully."
