#!/bin/zsh
# This script is used to deploy this folder dotfiles config to the right directories

# Define the base path for all configurations
BASE_CONFIG_PATH="$HOME/.config/"

CONFIG_FOLDERS=(
  "gnupg"
  "alacritty"
  "containers"
  "fuzzel"
  "git"
  "k9s"
  "mako"
  "sway"
  "sway-interactive-screenshot"
  "tmux"
  "waybar"
  "ncspot"
  "task"
)

# Create destination folders and symlinks for files in each folder
for folder in "${CONFIG_FOLDERS[@]}"; do
    echo $folder
  destination_path="$BASE_CONFIG_PATH$folder"
  mkdir -p "$destination_path"
  ln -sf "$DOTFILES/$folder/"* "$destination_path/"
  echo "Symlinked files in $folder to $destination_path"
done

# FILES
ln -sf "$DOTFILES/zsh/.zshrc" $ZDOTDIR
zcompile $ZDOTDIR/.zshrc
ln -sf "$DOTFILES/zsh/.p10k.zsh" $ZDOTDIR
zcompile $ZDOTDIR/.p10k.zsh
ln -sf "$DOTFILES/zsh/.zshenv" $HOME/.zshenv
zcompile $HOME/.zshenv
echo "Symlinked .zshrc .zshenv"
echo "recompile zcompile"
zcompile $ZDOTDIR/.p10k.zsh
zcompile $DOTFILES/zsh/fsh/fast-syntax-highlighting.plugin.zsh
zcompile $DOTFILES/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
zcompile $DOTFILES/zsh/vim.zsh
zcompile $DOTFILES/zsh/functions.zsh
zcompile $DOTFILES/zsh/aliases.zsh
zcompile $DOTFILES/zsh/exports.zsh
zcompile $DOTFILES/zsh/completions.zsh

echo "Creating user crontab"
# Specify the path to your dotfiles/cron folder
DOTFILES_CRON_FOLDER="$DOTFILES/cron"
# Create a temporary file for the new crontab
temp_crontab_file=$(mktemp)
# Loop through files in the dotfiles/cron folder and append them to the temporary crontab file
for cron_file in "$DOTFILES_CRON_FOLDER"/*; do
    if [ -f "$cron_file" ]; then
        cat "$cron_file" >> "$temp_crontab_file"
    fi
done
# Install the new crontab
crontab "$temp_crontab_file"
# Clean up the temporary file
rm "$temp_crontab_file"
echo "User crontab updated"

echo "Dotfiles deployment completed successfully."
