#!/bin/bash

WALLPAPER_PATH="$HOME/Pictures/wllppr.png"

curl -L "https://wallhaven.cc/api/v1/search?categories=111&purity=110&atleast=3840x2160&sorting=random" \
	-H "Accept: application/json" | jq -r '.data[0].path' | xargs curl -L -o "$WALLPAPER_PATH"

#curl -L 'https://picsum.photos/3840/2160' -o "$WALLPAPER_PATH"

echo "$WALLPAPER_PATH"
