#!/usr/bin/env bash

set -e

CONTEXT="$1"
NAMESPACE="$2"

if [[ -z ${CONTEXT} || -z ${NAMESPACE} ]]; then
	echo "Usage: $0 KUBE-CONTEXT NAMESPACE"
	exit 1
fi

RESOURCES="configmap secret daemonset deployment service hpa statefulset ingress"

echo "Dumping resources from namespace: ${NAMESPACE}"
for resource in ${RESOURCES}; do
	echo "Dumping resource: ${resource}"
	rsrcs=$(kubectl --context ${CONTEXT} -n ${NAMESPACE} get -o json ${resource} | jq -r ".items[].metadata.name")
	for r in ${rsrcs}; do
		echo "Dumped ${r}"
		dir="${CONTEXT}/${NAMESPACE}/${resource}"
		mkdir -p "${dir}"
		kubectl --context ${CONTEXT} -n ${NAMESPACE} get -o yaml ${resource} ${r} >"${dir}/${r}.yaml"
	done
done
