#!/bin/bash

# Get player status, suppress errors if playerctl is not available
player_status=$(playerctl -p spotify status 2>/dev/null)

# Replace problematic characters
artist=$(playerctl -p spotify metadata artist | sed 's/[&<>"]//g')
title=$(playerctl -p spotify metadata title | sed 's/[&<>"\]//g')

if [ "$player_status" = "Playing" ]; then
	echo "$artist - $title"
elif [ "$player_status" = "Paused" ]; then
	echo " $artist - $title"
fi
