#!/bin/bash

WP_FILE=$HOME/.config/wallpaper.jpg
wget -q -O $WP_FILE https://source.unsplash.com/1920x1080/?night,ocean,space,nature

if [[ -s "${WP_FILE}" ]]; then
    swaylock --image $WP_FILE
else
    swaylock -f -c 000000
fi
