#!/bin/bash

wallpaper_folder="$HOME/Pictures/upscaled/upscayl_png_realesrgan-x4plus-anime_4x/"

mapfile -d '' wallpapers < <(find "$wallpaper_folder" -type f -print0)

random_index=$((RANDOM % ${#wallpapers[@]}))

random_wallpaper="${wallpapers[$random_index]}"

echo "$random_wallpaper"
