#!/bin/bash

wallpaper_folder="$HOME/Pictures/favs/"

mapfile -d '' wallpapers < <(find "$wallpaper_folder" -type f -print0)

random_index=$((RANDOM % ${#wallpapers[@]}))

random_wallpaper="${wallpapers[$random_index]}"

echo "$random_wallpaper"
