[screenshot]
prompt = "📷> "
save_dir = "~/Pictures/Screenshots"
file_name = "screenshot_%Y-%m-%dT%H:%M:%S.png"
type = "png"
jpeg_quality = 100
png_level = 1
cursor = true

[screencast]
prompt = "📹> "
pid_file = "${XDG_RUNTIME_DIR}/sway-interactive-screenshot.${WAYLAND_DISPLAY}.video.pid"
save_dir = "~/Pictures/Screenshots"
file_name = "screencast_%Y-%m-%dT%H:%M:%S.mkv"
audio = "ask"

[notification_actions]
dragon.command = "dragon"
