k9s:
  liveViewAutoRefresh: true
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    skin: freak
    enableMouse: false
    headless: false
    logoless: false
    crumbsless: false
    noIcons: false
    reactive: false
  skipLatestRevCheck: false
  disablePodCounting: false
  logger:
    fullScreen: true
    tail: 1000
    buffer: 5000
    sinceSeconds: -1
    textWrap: true
