alias vim="nvim"
alias att="sudo pacman -Syyu --noconfirm;git -C $DOTFILES submodule update --remote;pipx upgrade-all;$HOME/.config/tmux/plugins/tpm/bin/update_plugins all;helm repo update;go-global-update; deploy_dot; fyi att-done"
alias update="source $HOME/.zshenv && source $ZDOTDIR/.zshrc && source $ZDOTDIR/.zprofile"
alias lcontext="kubectl config get-contexts"
alias ucontext="kubectl config use-context"
alias kubectl="kubecolor"
alias k="kubectl"
alias clima="curl wttr.in/Blumenau"
alias docker-compose="podman-compose"
alias ljunk="pacman -Qtdq"
alias s="exec sway"
alias essh="vim ~/.ssh/config"
alias docker="podman"
alias t="tmux attach || tmux new"
alias up="wg-quick up wg0"
alias down="wg-quick down wg0"
alias c="clear"
alias l="ls -lna"
alias ls='ls --color=auto'
alias cl="c;l"
alias grep="grep --color=auto"
alias ke="k8s_events | tabulate -1 -f fancy_grid | less -SR"
alias ka="k8s_alerts"
